import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Sidebar from "@/component/Sidebar";
import Header from "@/component/Header";
import Hydration from "@/stores/hydaration";

const poppins = Poppins({
  subsets: ["latin"],
  variable: "--poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Board App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable}  antialiased divide-y divide-[#E6E8EC] `}
      >
        <Hydration />
        <Header />

        <div
          className="flex divide-x divide-[#E6E8EC] h-full"
          style={{ height: "calc(100vh - 80px)" }}
        >
          <Sidebar />
          <main className="flex-1">{children}</main>
        </div>
      </body>
    </html>
  );
}
